blog/urls.py
from django.urls import path
from .views import HomeView, AboutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomeView, name='blog.home'),
    path('about/', AboutView, name='blog.about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coreSetting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('blog.urls'), name='blogApp'),
    path('account/', include('user.urls'), name='blogUser'),
    path('todolist/',include('ToDoList.urls'),name='todolist')
]

ToDoList/models.py
from django.db import models

# Create your models here.
class todoList(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    ACTION_CHOICES = [
        ("UN","Active"),
        ("D","Done"),
    ]
    action = models.CharField(choices=ACTION_CHOICES,max_length=2)

templates/about.html
{% extends "master.html" %}
{% block content %}
<h1>About Page</h1>
<a href="{% url 'blog.home' %}">Go to Home Page</a>
<a href="{% url 'blog.register' %}">Create an account</a>
{% endblock %}

templates/home.html
{% extends "master.html" %}
{% block content %}
<div style="border: 1px solid black;">
    <div>Name: {{ name }}</div>
    <div>Job: {{ job }}</div>
    <div>Age: {{ age }}</div>
    <div>Appearence: {{ appearence }}</div>
    <div style="text-decoration: underline;">Skills</div>
    <ul>
        {% for skill in skills %}
            <li>{{ skill }}</li>
        {% endfor %}
    </ul>
</div>
<div>
    <img src="{{ MEDIA_URL }}Flare.jpg" alt="">
</div>
<br>
<a class="btn btn-primary" href="{% url 'blog.about' %}">Go to About Page</a>
<a class="btn btn-primary" href="{% url 'blog.register' %}">Create an account</a>
<a class="btn btn-primary" href="{% url 'blog.login' %}">Login Account</a>
{% endblock %}

templates/login.html
{% extends "master.html" %}
{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <!-- <div>
        <label for="username">Username</label>
        <input class="form-control" type="text" id="username" name="username" placeholder="Enter username">
    </div>
    <br>
    <div>
        <label for="password">Password</label>
        <input class="form-control" type="text" id="password" name="password" placeholder="Enter password">
    </div> -->
    {{ form.as_div }}
    <br>
    <button type="submit">Create Account</button>
</form>
{% endblock %}

templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/register.html
{% extends "master.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <!-- <div>
        <label for="username">Username</label>
        <input class="form-control" type="text" id="username" name="username" placeholder="Enter username">
    </div>
    <br>
    <div>
        <label for="password">Password</label>
        <input class="form-control" type="text" id="password" name="password" placeholder="Enter password">
    </div> -->
    {{ form.as_div }}
    <br>
    <button type="submit">Create Account</button>
</form>
{% endblock %}

templates/todoListCreate.html
{% extends "master.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <br>
    <button type="submit">Create</button>
</form>
{% endblock %}

templates/todoListDelete.html
{% extends "master.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete?</p>
    {{ form.as_div }}
    <br>
    <button class="btn btn-danger" type="submit">Delete</button>
</form>
{% endblock %}

templates/todoListUpdate.html
{% extends "master.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <br>
    <button type="submit">Update</button>
</form>
{% endblock %}

templates/userhomepage.html
{% extends "master.html" %}
{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do List</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog.home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist.new' %}">Create New</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
    <div class="navbar-nav">
      <a class="nav-link nav-link" href="{% url 'blog.logout' %}">Logout</a>
    </div>
  </div>
</nav>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Task</th>
      <th scope="col">Action</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.title }}</td>
      <td>{{ item.description }}</td>
      <td>{{ item.get_action_display }}</td>
      <td>
        <a class="btn btn-warning" href="{% url 'todoList.update' item.id %}">Edit</a>
      </td>
      <td>
        <form action="{% url 'todoList.delete' item.id %}" method="post">
          {% csrf_token %}
          <button class="btn btn-danger">Delete</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}